### ISSUE TITLE
Discussion: Missing route /{ip}

### ISSUE THREAD

**Issue by nesc58** [9seconds/topographer#13]
Hi again,
thanks a lot for this great project. you shall be blessed

Years ago I have created a pull request to handle the following:
```
The route "/{ip}" is added to lookup a single IP via GET method. 
```

Is it possible to readd this route?

Background: 
From mine point of view it makes more sense to resolve a single IP due a GET Request instead of sending a  POST request filled with a single IP.
POST feels more like "Create a resource"
GET feels more like "Find something for me" 

Kind regards!

**Comment by 9seconds** [comment]
Sure, I've missed that. Will do!

**Comment by nesc58** [comment]
Works like a charm. Thank you so much
