### ISSUE TITLE
Some problems!

### ISSUE THREAD

**Issue by PekopT** [9seconds/topographer#4]
Hello! Awesome tool!

Some problems found:

1.
time="2018-11-20T22:04:22Z" level=warning msg="Cannot update provider" attempt=2 error="Cannot get download URL: Cannot extract download URL" provider=dbip

2.
time="2018-11-20T22:04:39Z" level=error msg="Cannot reopen provider database!" attempt=2 error="Incorrect IP range: Node Busy" provider=software77

3. https://hub.docker.com/r/nineseconds/topographer/builds/bybx9fnfpitnabjrgxymqeh/

Can we expect this to be fixed?))

Thanks!

**Comment by PekopT** [comment]
@9seconds Сергей?

**Comment by 9seconds** [comment]
Привет! К сожалению, я только на выходных смогу заняться этими проблемами. Да, пофикшу, все будет. Не увидел нотификации раньше, пропустил.

**Comment by PekopT** [comment]
@9seconds привет!) есть подвижки?

**Comment by 9seconds** [comment]
Вроде починил. Но, смотрю, сейчас много чего поменялось в этих сервисах; видимо, нужно будет закатать рукава и провести полную ревизию

**Comment by PekopT** [comment]
@9seconds 

```
# docker build -t topographer .
Sending build context to Docker daemon  265.7kB
Step 1/12 : FROM golang:alpine AS build-env
 ---> 57915f96905a
Step 2/12 : RUN set -x   && apk --update add git make
 ---> Using cache
 ---> a5fafff9d93f
Step 3/12 : ADD . /go/src/github.com/9seconds/topographer
 ---> 30a46c2c4e24
Step 4/12 : RUN set -x   && cd /go/src/github.com/9seconds/topographer   && make clean   && make -j 4
 ---> Running in 9092609a19a6
+ cd /go/src/github.com/9seconds/topographer
+ make clean
HEAD is now at 4d4e19f Merge pull request #5 from 9seconds/fixes
+ make -j 4
make: *** No rule to make target 'vendor', needed by 'topographer'.  Stop.
The command '/bin/sh -c set -x   && cd /go/src/github.com/9seconds/topographer   && make clean   && make -j 4' returned a non-zero code: 2
```

**Comment by 9seconds** [comment]
Стыдоба-то какая. Пофиксил
